# 실험 종합 기록 (Master) — SWRL / RHUKF-FV 프레임워크

> **단일 종합 문서.** 왜 하는지 → 실측/확정값 → 시간순(무엇을·측정·결과) → 다음.
> **과거 실측값 참조는 항상 여기 Ⅱ절부터.** 설계 전 반드시 확인.
> 물리·정합 상세: `SIM_ALIGNMENT.md`. 서사·로드맵: `CLAUDE.md`. 공격모델: `ATTACK_INJECTION.md`.
> (구 `RESULTS_LOG_20260820.md` + `RESULTS_20260821_GYRO_POMDP.md` 통합)

---

# Ⅰ. 왜 (프로젝트 목적)
- **메인 기여 = SWRL(RHUKF-FV) 옵티마이저** — Adam 대비 sparse-attack 샘플효율·노이지환경 강건성 우위. **탐지 자체가 기여 아님**(탐지는 임계값으로도 어느정도 됨).
- 프레임워크: UAV 액추에이터 공격 탐지를 **POMDP/QCD stopping** 으로 정식화. UKF 잔차(NIS) 관측 DDQN이 매 스텝 track/hover 이진 결정 + **복귀**(양방향 stopping).
- RHUKF 우위를 보이려면 **노이지 학습환경**이 필요한데, **인위적 주입은 안 함** — 프레임워크 내에서 자연 발생해야 함(급기동→gyro, 강풍→vel).

---

# Ⅱ. 실측 / 확정값 참조표 ★★ (설계 전 반드시 여기부터)

## 공격 (swrl_config.py)
| 항목 | 값 | 비고 |
|---|---|---|
| 타입 | torque **틸트 FDI** (roll+pitch 랜덤방향, thrust=0, yaw=0) | 궤적이탈. 추력공격 배제(호버가 못흡수=프레임깨짐) |
| 크기 δ | **0.4~0.8 권한비(정규화)** `attack_delta_range` | 밴드 실측 |
| δ→Nm | `attack_tq_authority_nm=4.36`. 샘플러 gx=δ×4.36 → tilt `tqx=gx/4.36` | ⚠**sweep 주입 시 value=δ×4.36** (0.4→1.74/0.6→2.62/0.8→3.49) |
| 버스트 | ON randint(4,10)/OFF randint(4,8)@10Hz, 에피당 2~4개, const 30% | |
| 주입점 | ControlAllocator c[0](배분 직전 정규화 wrench). sim=실기 동일 | ATTACK_INJECTION.md |

## 바람 / 외란 (swrl_config.py, 확정 2026-07-22·강풍 08-19)
| 항목 | 값 |
|---|---|
| 분포 | none 40% / wind_turbulence 60% (`disturbance_weights [0.4,0.6]`) |
| 2-tier | 약풍 75% `(0.5,2.0)` / 강풍 25% `(6.0,12.0)` m/s |
| 힘 | ws6=1.1N, ws12=4.5N (ws15=7N=53%→추락) |
| 추락한계 | 전 패턴 **ws10까지 0% 추락**. ws12: aggr/f8/wp 50%·hover25%·circle0%. **ws9는 강풍tier 안, 안전** |
| 모델 | OU(Ornstein-Uhlenbeck), ti=0.5 tb=2.0. **시작 스파이크 아님(0에서 램프업)**. gust/스파이크 바람=실측근거 없음→안씀 |

## 센서 / 필터 (SIM_ALIGNMENT.md)
| 항목 | 값 | 비고 |
|---|---|---|
| 센서 σ | gyro[.066,.070,.044]·GPS수평0.9×·수직0.219 (UKF단, `SENSOR_NOISE_SCALE`) | 실기 실측. gyro NIS엔 거의 무영향(R≫σ²) |
| UKF R/Q | **R_gyro 0.2 · R_vel 0.1 · Q_gyro 5e-3** | 고집(R≫σ²0.0044). 노이즈입력서도 최적 불변. Q↓는 악화(§Ⅲ) |
| 압축 | `min(log(1+√NIS), 3)` = 마할라거리 log1p clip3, [0,3] | 온셋 d′ 2.48 |

## 플랜트 (calibration.json / run_sim.py — 상세 SIM_ALIGNMENT.md)
C_thrust 40.3 · C_torque(x,y,z) 3.26/3.1/1.378 · mass 1.34kg · MOTOR_TAU 0.014(=실기 23ms, 2배적용) · THR_MDL_FAC 0.78 · UKF I=플랜트 I(동일 calib).

## 학습 (swrl_config.py)
리워드 FN 딜레이 그래디언트(−0.4~−3.87 온셋가중)·TP/TN +0.5·FP −1·term −2.5 (v4) · RHUKF r_init1.0/p_delta0.02/q1e-4/huber3/tau0.005 (수렴 T_Var 1.2) · net [24,24] 962params/12D obs/window4.

---

# Ⅲ. 시간순 실험 기록 (무엇을 → 측정 → 결과)

## 2026-08-19 — Adam baseline + 관측 압축 확정
- **무엇**: 관측 압축 v1~v4 비교, Adam baseline 학습.
- **결과**: 압축 `log(1+√NIS)clip3`(v4)가 최적 — delay 2.0·d≤2 100%·F1 0.88·FP 0.001. (압축 포화가 병목이었음).
- **v5 페어(RHUKF vs Adam 동일조건)**: 둘 다 F1~0.88·delay2. 샘플효율 RHUKF 0.7@48 vs Adam 57(미미). → **clean 환경은 안 갈림** = 노이지 환경 필요.

## 2026-08-20 — gyro가 기동에 안 튄다 (프레임워크 재설계 트리거)
- **측정**: 패턴별 benign gyro NIS p90 = **0.1~0.37 (전 패턴, aggressive 포함)**. 기동이 gyro aliasing 안 만듦. ("gyro p90 120"은 공격 회복구간 오염이었음).
- **부수**: 센서 σ 주입은 gyro NIS 거의 무영향(R≫σ²). Q/R 재튜닝해도 R0.2/Q5e-3 불변. 바람 추락한계 ws≤10 survivable.
- **전략 결정**: 메인=옵티마이저. 자연 노이즈원 ①기동→gyro ②강풍→vel. 인위적 주입 X.

## 2026-08-21 — gyro 정밀진단 · 가감속 · Q/R · POMDP

### (1) 왜 gyro가 안 튀나 — 정밀진단
- **다이나믹스·캘리브 정상.** gyro 예측이 **명령토크 u/I**를 씀 → 플랜트도 같은 명령토크 실행 + I·C 동일 → UKF가 "예측"이 아니라 같은 입력을 같은 모델로 한 스텝 굴림 → 맞을 수밖에. 고집(R↑)은 예측이 이미 맞아 공짜.
- **핵심 물리**: gyro 잔차 ∝ 명령토크(각가속). **등속회전=정상상태 토크0=완벽예측=깨끗. 가감속=토크≠0=모터지연 물려 잔차.**

### (2) 가감속 vs 등속 — 전 패턴 (속도변조 노브 `SPEED_MOD_AMP` 구현)
- **측정(ws0 순수기동) gyro NIS 피크(p90) 등속vs가감속 배율**: circle 1.0 · figure8 1.0 · aggressive 1.4 · **waypoint 5.0(코너 급정지)**.
- **결과**: gyro aliasing ∝ **기동 sharpness**. 매끄러운 circle/figure8은 속도변조 넣어도 약함(~1.3). **날카로운 코너/급정지(waypoint)만 강함.**
- **바람 효과(ws0→ws12 피크)**: gyro 0.2→1.0(버펫팅), **vel 0.4→11(27배=바람 주채널)**.

### (3) Q/R로 gyro aliasing 못 늘림 (offline Q스윕)
```
Q_gyro  평시등속 평시기동 기동/등속비 공격d′
5e-3    1.97    107    54.3★    1.56★   ← 현행이 최적
1e-4    145     3497   24.1     0.86    ← 바닥폭증·분리악화·d′하락
```
- **Q↓는 스케일만 바꾸고 분리도 악화 + 공격 d′ 하락. R↓는 고집약화로 추가악화. → Q/R 건드리지 말 것.** 잔차는 모델오차(기동·바람)로만 커짐.

### (4) 기각된 레버
속도1.5배(등속이라 무효) / 모터지연↑(이미 정합) / I·C불일치·cal-error(모델오차 주입 안함) / Euler채널(측정불가) / Q·R↓(악화) / 충격·스파이크바람(실측근거 없음).

### (5) POMDP 분석
- POMDP = 공격 NIS ≈ 평시 NIS **겹쳐야** 성립. 강한 공격(100+)은 trivial(MDP).
- **긴장**: consequential(추락)⟹강함⟹탐지쉬움. 약하면 PX4 보상→무해.
- **해법**: 약한 공격(밴드 δ0.4~0.8)을 **바람+날카로운 기동 중** 주입 → 약해도 결과성 + gyro가 노이즈에 묻힘=POMDP + 고집UKF 잔차남김(탐지가능). **noise=POMDP의 핵심.**
- **[진행] tilt 밴드 스윕**: waypoint+바람ws9+δ{0,0.4,0.6,0.8} → 결과성밴드 ∧ per-step겹침(non-trivial) ∧ windowed분리(RL명분) 측정 중.


### (6) ★ tilt 밴드 스윕 판정 (2026-08-21 완료) — gyro 탐지는 trivial 확정
waypoint+바람ws9+tilt δ{0,0.4,0.6,0.8}:
```
δ    track생존 hover생존 | 공격gyro압축 | d′gyro d′vel
0.4    1.00     1.00     |   2.61      | 13.1   1.98   비결과성
0.6    1.00     1.00     |   3.00      | 14.7   2.04   비결과성
0.8    0.00     1.00     |   3.00      |  5.9   2.06   ★결과성
       benign gyro: p50 0.36 p90 0.58
```
- 결과성 밴드(waypoint+ws9)=δ0.8. 밴드에서도 **gyro d′5.9~14.7=trivial**(benign0.36 vs 공격3.0클립).
- **결과성 ∧ gyro애매 밴드 없음** — tilt는 어떤 크기든 gyro 포화. benign gyro 최대~1.0라 항상 갭.
- vel은 애매(d′2, 바람겹침)이나 gyro로 이미 잡혀 탐지엔 잉여.
- **판정: 순수 tilt로 per-step 탐지는 trivial. non-trivial화 불가.**
- → **프레이밍 확정**: 탐지난이도 아님. **최적 순차응답(선언+복귀타이밍) 하의 옵티마이저(RHUKF vs Adam) 우위.** plot `results_tilt_band_overlap.png`.

### (7) 관측·rate 구조 정당성 (2026-08-21)
**rate 구조:**
- sim 물리 **250Hz** (Isaac PhysX + PX4 SITL lockstep). 실기 Pixhawk6C: `IMU_GYRO_RATEMAX 800Hz`(rate루프)/`INTEG 200Hz`/attitude~250/pos~50Hz.
  → sim rate루프(250Hz)는 실기(800Hz)보다 3배 느리나, **MOTOR_TAU=0.014를 실기 오토튠 a2=0.67에 맞춰 유효 회전동역학 정합**. 우리 10Hz 탐지엔 무영향(둘 다 10Hz보다 빠름).
- **UKF: 50Hz predict+gyro, 10Hz GPS. 관측/결정: 10Hz** (GPS fresh 게이트).

**UKF 50Hz 정당:** companion 탐지필터(제어기 아님). burst 공격(0.4~1.0s)=저주파라 50Hz(Nyquist 25Hz)로 충분(버스트당 20~50샘플). u 50Hz샘플이 fast rate루프를 앨리어싱하나 **benign·공격 일관 → 바닥일 뿐, 탐지 유지**. 실기 companion도 50Hz면 정합. ⚠확인: 실기 PX4→companion 발행rate.

**10Hz 관측 정당:** vel/pos가 GPS(10Hz)에서만 fresh → **가장 느린 채널(vel)이 새 정보 주는 순간에 결정** = 자연. 모드결정은 10Hz면 충분(빠른 제어는 PX4). burst는 10Hz로 잡힘. gyro는 50→10 다운샘플이나 **지속 burst엔 무손실**(지연바닥 100ms, sub-100ms 순간공격이면 부족—현재 무관).

**★ vel 채널에 공격 실리나 (실측, 시간창 공격만구간=바람OFF, arm0.04):**
```
ws | clean_g 공격만_g | clean_v 바람만_v 공격만_v
4  | 0.28    2.81    | 0.28    0.31     1.19   ← vel 0.28→1.19(4배)
10 | 0.27    2.62    | 0.27    0.56     1.28
```
- **공격이 vel에도 실림**(표류: tilt→수평가속→drift). 단 gyro(10배)보다 **약함(4배)** — UKF가 gyro로 자세추종→표류 일부예측→vel엔 **지연잔여(2차)만**.
- **∴ vel 관측 정당**: 실제 공격 2차신호(1.2) + 바람 애매성(POMDP) 담당. 두 채널 역할분담: gyro=강한직접(easy), vel=약한표류+바람애매(hard).

### (8) ★ 회전바람 + 시간창 grid (2026-08-21 완료) — POMDP는 vel, gyro는 easy 확정
**회전바람 구현**: `WIND_MOMENT_ARM=0.04` (τw=arm×F, ws²·난류 비례). Q250 CP오프셋 근사. arm 고정, ws만 스윕.
**시간창**: clean(0-100)→바람(100-300)→공격(180-380)→복귀. `WIND_START/END`,`SWEEP_ATK_START/END`,`EP_MAX_STEPS=450`.
**grid**: 전패턴 × ws{4,6,8,10,12} × δ{0.4,0.6,0.75,0.8} × 2ep. (clean이륙 → 이륙타임아웃 0회, 구 hijack 85회 대비 대폭 빠름)

**Survivable 밴드 (공격끝까지 생존, 전패턴):**
```
δ    ws4  ws6  ws8  ws10  ws12
0.4  1.0  1.0  1.0  0.88  0.17
0.6  1.0  1.0  1.0  0.38  0.17    ← 학습환경 = δ≤0.6 ∧ ws≤8 (ws10 경계)
0.75 0.25 0.38 0.25 0.0   0.0     ← 추락(결과성 밖)
0.8  0.0  0.0  0.0  0.0   0.0
```

**회전바람이 gyro/vel 올림 (바람만 구간, 공격없음):**
- gyro: ws4 0.28 → ws12 ~1.0~1.25 (rotational wind aliasing 확증)
- vel : ws4 0.30 → ws12 ~0.75~0.95

**★ d′(공격 vs 바람, δ0.6, per-step):**
```
ws | d′gyro d′gyro_win | d′vel
4  | 29.7   27.2       | 7.4
8  | 13.7   13.5       | 4.6
10 |  8.5    8.1       | 2.5    ← vel 애매(POMDP)
12 |  7.8    7.7       | 2.2
```
- **gyro: 회전바람이 d′ 좁혔으나(29.7→7.8) 여전히 분리(trivial). 공격(3.0)≫바람(1.0).** = easy 채널.
- **vel: ws10~12서 d′ 2.2~2.5 = 애매(POMDP 채널).** 공격(1.25)↔바람(0.75) 겹침. 전패턴 동일.

**결론(확정):** 회전바람으로 gyro 바닥은 올랐지만 gyro는 여전히 easy(공격 강함). **POMDP 난이도 = vel(바람↔공격 겹침, ws≥10) + 복귀타이밍.** → 프레이밍 = **vel 애매 + 순차복귀 하의 옵티마이저(RHUKF vs Adam)**. plot `results_timewin_timeseries.png`, 표 `results_timewin_summary.txt`.

---


### (9) ★★ 밴드 재정의 = track추락 ∧ hover생존 + 축의존 (2026-08-22 완료)
**핵심 교정**: 이전(8)의 "survivable 밴드"는 **track 생존**만 봤다 — 틀렸다. 밴드는 **"공격만으로는(track) 추락하나 호버로 안정화(hover)되면 생존"** 하는 영역이다(프레임워크 조건③ 대응가능성). hijack이 track·hover 셀을 둘 다 캡처하므로 **track추락(<0.5) ∧ hover생존(>0.5)** 로 재산출.
**grid**: `arm0.02` · `Q_gyro2e-3` · 관측 min(log(1+√NIS),3) · 전4패턴 × δ{0.3-0.8} × ws{0,4-12} × **ep3** · 공격=**지속20초**(SWEEP_BURST off) · 공격 2형태(**단일축 roll** / **동시축 roll=pitch 45°**, 같은 magnitude δ=√(roll²+pitch²)).
스크립트 `etc/scripts/axis_compare.sh` / 분석 `etc/scripts/axis_band_analysis.py`.

**★ hover(대응)는 거의 전 영역 생존 — 방어 fallback이 강건함:**
```
hover 생존: 단일축=δ0.8 ws12(0.0)·ws11(0.7) 외 전부 1.0 / 동시축=전 영역 1.0
```

**단일축(순수 roll) — track생존 / hover생존 / 밴드:**
```
        track(공격만 ws0 → ws12)              밴드(track추락∧hover생존)
δ0.5  1.0 ......... 0.9(ws10) 0.6 0.2        ws12=밴드
δ0.6  1.0 ......... 0.8(ws10) 0.4 0.2        ws11,12=밴드
δ0.7  1.0 ..0.9(ws7).. 0.6(ws10) 0.2 0.2     ws11,12=밴드
δ0.8  0.0 (전 ws 추락!)                       ★ws0~11=밴드 (ws12만 hover도 추락)
```
→ **단일축 δ0.8 = 결과성 밴드의 중심**: 공격만으로 track 추락, hover가 ws11까지 구제.

**동시축(roll=pitch 45°) — 같은 δ인데 결과성 약함:**
```
δ0.8  track: ws0=1.0(생존!) ws8=0.8 ws10=0.4 ws12=0.1    hover: 전부 1.0
      → 밴드 = ws10~12 (바람 있어야 결과성)
```

**★ 축의존 = 결과성은 총 magnitude가 아니라 축별 성분이 결정:**
```
밴드차(동시축 track − 단일축 track):
  δ0.3~0.7 : ~0.0 (방향무관 — 둘 다 공격만으론 안 죽음)
  δ0.8     : +1.0 (ws0~7)  ← 단일축 추락 / 동시축 생존, 정확히 여기서 갈림
```
= 추락은 **한 축 틸트가 임계(~δ0.8/축)를 넘을 때** 발생. 단일축 δ0.8=roll 0.8(초과). 동시축 δ0.8=축별 0.566(미달). 동시축이 추락하려면 축별≈0.8 → 총 δ≈1.13 필요.

**공격구간 NIS(압축 중앙값):** gyro **3.0 포화**(양 축모드 공통, easy) / vel 단일축 **1.2** · 동시축 **1.3~1.4**(동시축이 vel 약간↑ — 대각표류가 더 큼).

**상한 확정**: 공격 **δ≤0.8** · 바람 **ws≤10~11**(단일축 δ0.8 hover가 ws11까지, ws12서 붕괴).
**⚠ 지속20초 vs burst**: 이 grid는 결과성(track추락)을 뚜렷이 보려 **지속20초**. 학습은 burst(ON4-10/OFF4-8)라 OFF-gap서 복귀결정 발생 — 결과성은 지속이 확립, 복귀는 burst가 담당.
plot: `axis_band_heatmap.png`(track/hover/밴드 6패널) · `axis_nis_heatmap.png` · `axis_timeseries.png`. 표 `results_axis_band_summary.txt`.
**★★ burst(간헐 FDI) 대비 — 결과성이 약해진다 (2026-08-22 완료):**
학습은 `SWEEP_BURST=rand:4,10,4,8`(ON~U(4,10)/OFF~U(4,8) 스텝) = 표준 간헐 FDI. 지속20초와 밴드경계(δ{0.6,0.7,0.8}×ws{0,8,12}×4패턴×ep2) 비교:
```
                track 생존 (지속 → burst)
단일축     ws0(공격만)    ws8        ws12
 δ0.6      1.0→1.0      1.0→1.0    0.2→0.6
 δ0.7      1.0→1.0      0.9→1.0    0.2→0.1
 δ0.8     ★0.0→0.9    ★0.1→0.8    0.0→0.0
```
- **★ 단일축 δ0.8 attack-only: 지속=추락(0.0) → burst=생존(0.9).** OFF-gap(4-8스텝)마다 PX4가 틸트를 회복 → 드리프트 누적 안 됨. burst는 per-burst 회복가능.
- **hover는 burst서 전역 생존**(지속선 죽던 단일축 δ0.8 ws12도 burst hover=1.0 — OFF-gap 회복).
- **burst 밴드 = 고풍(ws12)만**: δ0.7-0.8 ws12서 track추락(0.1-0.2)∧hover생존(1.0). attack-only·mid-wind burst는 **비결과성**(track 생존).
- 공격 NIS 동일(gyro 3.0 포화 / vel 1.2-1.4). 탐지 신호는 지속=burst 동등(ON구간 잔차 동일).

**함의**: 간헐 FDI는 per-burst 회복돼 **crash-결과성이 약하다** → burst 단독 밴드는 얇음(고풍 ws12). 결과성을 확보하려면 (a)지속/장버스트, (b)burst+고풍 결합, (c)crash 대신 **궤적이탈**을 결과성으로. OFF-gap은 복귀결정(POMDP)의 근원이자 동시에 결과성을 지우는 양날 → 프레임워크 결과성 정의(추락 vs 이탈) 재검토 필요.
plot `burst_band_heatmap.png` / `burst_timeseries.png`(펄스 시그니처) / 표 `results_burst_band_summary.txt`.


---


# Ⅳ. ★ 확정 프레임워크 + 실측 종합표 (2026-08-21)

## 확정 프레임워크 (실측 근거로 확정)
- **주행 궤적**: 전 4패턴 — circle · figure8 · waypoint · aggressive
- **공격**: tilt(단일축 roll / 동시축 roll=pitch, thrust=0) · **δ 0.4~0.8**(밴드=track추락∧hover생존) · value=δ×4.36(단일)/δ×3.083(동시) · burst ON4-10/OFF4-8
- **바람**: turbulence + **회전성분(WIND_MOMENT_ARM=0.04)** · **ws 4~8** (survivable, ws10 경계) · 2-tier(약0.5-2/강6-12)
- **시간창**: clean → 바람 → 겹침 → 공격 → 복귀 (WIND_START/END·SWEEP_ATK_START/END)
- **관측**: [nis_vel, nis_gyro, action]×window4 · 10Hz(GPS gate) · 압축 min(log(1+√NIS),3)
- **채널 역할**: **gyro=easy 탐지 anchor** (공격 강함) / **vel=POMDP 애매채널**(바람↔공격, ws≥10) / **+복귀 타이밍**(순차 애매)
- **★밴드 정의**: track추락(무대응) ∧ hover생존(대응) = 조건③. 단일축 δ0.8=밴드중심(hover ws11까지 구제) / 동시축은 바람 있어야 결과성(축의존, Ⅲ-9)
- **hover(방어)**: 거의 전 밴드서 생존 = fallback 강건. 단일축 δ0.8 ws12만 붕괴
- **본실험**: RHUKF-FV vs Adam (+CUSUM baseline) — 이 노이지 POMDP서 샘플효율·강건성

## 실측 종합표 (궤적 × 바람, δ0.6) — gyro/vel 각 구간이 어떻게 튀나 + 생존
### 궤적별 × 바람별 gyro/vel/생존 (δ0.6, 압축[0,3])
| 궤적 | ws | gyro평시 | gyro바람 | gyro공격 | vel바람 | vel공격 | 생존 |
|---|---|---|---|---|---|---|---|
| circle | 4 | 0.28 | 0.25 | 3.00 | 0.31 | 1.26 | 1.00 |
| circle | 6 | 0.27 | 0.26 | 3.00 | 0.35 | 1.24 | 1.00 |
| circle | 8 | 0.28 | 0.49 | 3.00 | 0.46 | 1.31 | 1.00 |
| circle | 10 | 0.28 | 0.66 | 3.00 | 0.58 | 1.27 | 0.50 |
| circle | 12 | 0.29 | 0.94 | - | 0.81 | - | 0.00 |
| figure8 | 4 | 0.28 | 0.34 | 2.99 | 0.32 | 1.19 | 1.00 |
| figure8 | 6 | 0.28 | 0.44 | 2.99 | 0.42 | 1.20 | 1.00 |
| figure8 | 8 | 0.28 | 0.71 | 2.99 | 0.49 | 1.23 | 1.00 |
| figure8 | 10 | 0.28 | 0.87 | 3.00 | 0.68 | 1.56 | 0.00 |
| figure8 | 12 | 0.28 | 0.98 | - | 0.69 | - | 0.00 |
| waypoint | 4 | 0.31 | 0.39 | 3.00 | 0.34 | 1.25 | 1.00 |
| waypoint | 6 | 0.31 | 0.47 | 3.00 | 0.38 | 1.25 | 1.00 |
| waypoint | 8 | 0.31 | 0.68 | 3.00 | 0.47 | 1.24 | 1.00 |
| waypoint | 10 | 0.30 | 0.75 | - | 0.58 | - | 0.00 |
| waypoint | 12 | 0.31 | 0.87 | 2.99 | 0.69 | 1.34 | 0.50 |
| aggressive | 4 | 0.26 | 0.37 | 2.99 | 0.31 | 1.29 | 1.00 |
| aggressive | 6 | 0.25 | 0.58 | 2.99 | 0.37 | 1.29 | 1.00 |
| aggressive | 8 | 0.25 | 0.60 | 2.99 | 0.48 | 1.32 | 1.00 |
| aggressive | 10 | 0.27 | 0.83 | 2.99 | 0.61 | 1.25 | 1.00 |
| aggressive | 12 | 0.25 | 0.78 | 3.00 | 0.68 | 1.21 | 1.00 |
※ gyro평시≈0.28 일정 · gyro바람=회전바람 aliasing(ws↑) · gyro공격=포화3.0(easy) · vel공격=1.25(2차, 표류) · '-'=그 셀 추락으로 공격구간 데이터 없음

## 생존 매트릭스 (δ × ws, 전패턴 평균) — 공격 끝까지 생존율
| δ＼ws | 4 | 6 | 8 | 10 | 12 |
|---|---|---|---|---|---|
| 0.4 | 1.00 | 1.00 | 1.00 | 0.88 | 0.25 |
| 0.6 | 1.00 | 1.00 | 1.00 | 0.38 | 0.38 |
| 0.75 | 0.25 | 0.38 | 0.25 | 0.00 | 0.00 |
| 0.8 | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 |
→ **survivable = δ≤0.6 ∧ ws≤8**. aggressive만 ws12까지 강건. figure8/waypoint는 ws10서 추락.

## 핵심 읽기 (표 요약)
- **gyro**: 평시 0.28 → 회전바람 0.9(ws12) → 공격 **3.0 포화**. 회전바람이 바닥 올려도 공격이 압도 = **분리 유지(easy)**.
- **vel**: 바람 0.3→0.8 → 공격 **1.25**. ws≥10서 바람↔공격 근접(d′ 2.2~2.5) = **POMDP**.
- **생존**: δ0.6·ws≤8 전패턴 생존. aggressive 최강건(ws12), figure8/waypoint ws10 추락.

# Ⅴ. 현재 상태 / 다음
- [완료] 밴드 재정의(track추락∧hover생존) + 단일/동시축 지속grid(arm0.02,Q2e-3,ep3) → **지속 단일축 δ0.8=밴드중심**, hover 거의전역 생존, gyro=easy·vel=POMDP, 축의존. 상한 δ≤0.8·ws≤10~11 (Ⅲ-9).
- [완료] **burst(rand:4,10,4,8) 대비** → 간헐FDI는 per-burst 회복돼 **crash-결과성 약함**: 단일축 δ0.8 attack-only 지속0.0→burst0.9 생존. burst 밴드=고풍ws12만. hover 전역생존.
- [★결정필요] burst 단독은 crash-결과성 얇음. 결과성 정의(추락 vs **궤적이탈**) 또는 지속/burst+고풍 중 택. OFF-gap=복귀POMDP 근원↔결과성 소거의 양날.
- [다음] 판정 후: "탐지 non-trivial(밴드공격이 노이즈와 겹침)" 확인되면 → 그 세팅으로 **RHUKF vs Adam 본실험**(노이지 POMDP).
- [서사] 탐지가 아니라 **최적 순차응답(선언+복귀 타이밍) 하의 옵티마이저 우위**로 프레이밍.

## 산출물 인덱스
- plot: `axis_band_heatmap.png`(track/hover/밴드 6패널) · `axis_nis_heatmap.png` · `axis_timeseries.png` · `results_sm2_*.png`(가감속)
- 표: `results_sm2_summary.txt`
- offline 도구: `scratchpad/offline_ukf_sweep.py`(I/C/Q/R 재구동) · `analyze_speedmod2.py` · `tilt_band_analysis.py`
- 메모리: `gyro-clean-maneuver-diagnosis-20260821` · `speedmod-accel-decel-gyro-20260821`

---


# Ⅵ. ★★ 최종 확정 프레임워크 (2026-08-23)

> 아래는 전 측정을 종합한 **확정 스펙**이다. Q_gyro만 fine sweep(1e-3~1e-2) 검증 대기(잠정 2e-3).
> 목적 재확인: **자연 POMDP 노이즈 + RL 자체 노이즈에서 RHUKF-FV가 Adam보다 강건·샘플효율 우위** — 탐지가 아니라 **최적화기 비교**가 기여.

## 확정 스펙
| 항목 | 확정값 | 근거 |
|---|---|---|
| **주행 궤적** | 4패턴 (circle·figure8·waypoint·aggressive) | 기동 aliasing=RL 노이즈원. aggressive=최취약(공격 최흡수·최대 aliasing), circle/waypoint=최취약추락 |
| **공격 형태** | tilt FDI (roll/pitch, 방향 α~U(0,2π)) | wrench c[0] 주입. 추력공격 배제(hover 못흡수) |
| **공격 세기 δ** | **연속 U(0.1, 0.8)** (0.05격자 아님) | δ0.1=탐지가능하한(gyro1.78>바람1.44), **δ0.05 제외**(gyro1.24<1.44=탐지불가·바람과 겹침). δ0.8=결과성상한. value=δ×4.36. 방향 α~U(0,2π) 연속 |
| **공격 시간(burst)** | **ON~U(5,20)스텝(0.5-2s) / OFF~U(10,30)스텝(1-3s)** | ON>데드라인(d≤3)+드리프트 시작, OFF=복귀결정+CUSUM붕괴. 공격창 내 4-6버스트 |
| **바람** | 회전(arm0.02) turbulence, **2-tier: 약풍 0.5-2(~65%)/강풍 4-10(~35%)** | ws≤10=hover 구제상한. 강풍서 vel↔공격 겹침=POMDP. 평온TN 확보 위해 2-tier |
| **필터 Q** | gyro **2e-3 확정** ⚠(실제 학습은 5e-3 — Ⅷ-5 불일치 미해소) · vel 5e-3 · euler 5e-4 · pos 1e-3 | ★sweep완료(1e-3~1e-2): aliasing 2e-3서 봉우리(0.689) + vel d′ 유지. 1e-2는 vel d′ 붕괴(0.6) |
| **필터 R** | vel 0.1 · gyro 0.2 · pos 0.5 | R≫센서σ²(12~250배)=shadow UKF. 공격을 잔차로 노출 |
| **관측 압축** | **min(log(1+√NIS), 3.5)** | 3.0→3.5(gyro공격 상단 3.0-3.7 펼침). 약공격δ0.1-0.3이 중간(1.8-2.8) 채움 |
| **관측 벡터** | [nis_vel, nis_gyro, action]×window4 = 12D · 10Hz(GPS gate) | 불변 |
| **에피소드** | **400스텝 = 40초** (10Hz) | clean 10s + 바람/비행 + 공격창 15-20s(버스트) + 복귀 5-7s |
| **에피소드 총수** | **~300ep** × seed≥3 (저데이터 체제) | 300ep=샘플효율을 시험하는 짧은 예산. RHUKF의 조기수렴 우위가 드러나는 지점 |
| **reward** | 현행(탐지기반 TP/TN/FP/FN + FN초반가중 + terminal) | 결과성과 분리 — 관측에 공격 실리면 학습. RL은 결과성 안 봄 |
| **탐지 baseline** | CUSUM(채널별,FPR보정) + 고정임계 | 학습된 RL 탐지기 vs 고전 탐지기. 지표 TP/지연/FP/복귀 |
| **최적화기 비교(★기여)** | **RHUKF-FV vs Adam vs SGD vs EKF** | DDQN을 학습하는 옵티마이저. 500ep 저데이터서 샘플효율+강건성 |

## 실측 근거 종합 (2026-08-23)
**약공격 landing (단일축 지속, gyro/vel 압축NIS):**
```
δ    gyro   vs바람(1.44)  vel    생존
0.05 1.24   겹침★         0.35   생존
0.10 1.78   경계          0.50   생존   ← δ_min. 중간채움 시작
0.15 2.13   분리          0.74   생존
0.20 2.39   분리          1.15   생존
0.30 2.76   분리          1.17   생존
0.50 3.00   포화          1.17   생존
0.80 3.00   포화          1.11   추락(단일축)
```
= 약공격 δ0.1-0.3이 **빈 중간(1.8-2.8) 채움**. δ0.05만 바람과 겹침. δ0.8만 결과성.

**CUSUM baseline (FPR 1%, RL 목표선):**
```
              탐지지연   미탐률
지속: gyro    4스텝      1%    (easy)
      vel     26스텝     5%    (POMDP)
burst: gyro   24스텝     16%   ← 간헐이 CUSUM 붕괴
       vel    38스텝     17%
```
= **RL이 이길 무대 = 간헐(burst) + vel + 복귀**. 지속 gyro는 CUSUM도 쉬움(무해, easy anchor).

**Q_gyro sweep (1e-3~1e-2, aggr δ0.5) — 2e-3 확정:**
```
Qg     공격g  aliasing(ws8)  감쇠g/v   d′ g/vel
1e-3   3.00   0.661          16/50    17.0/4.4
2e-3   3.00   0.689★최고     10/41    17.1/4.1  ← 확정(aliasing 봉우리)
5e-3   2.82   0.412          6/33     16.9/3.9
1e-2   2.49   0.326          5/24     17.1/0.6  ← vel d′ 붕괴(자세→vel 결합흡수)
```
= aliasing(RL노이즈)은 2e-3서 최대, 높이면 vel-POMDP 파괴. Q_vel: 1e-3(공격1.71,POMDP약화)/5e-3(1.17,유지★)/2e-2(0.75,흡수).

**vel 오프셋 감쇠 (공격끝 step380 후):**
```
gyro: 2스텝(0.2s) 급락    vel: 40-60스텝(4-6s) 완만
```
= vel 느린 감쇠는 물리(드리프트 회복)=**복귀 안전신호**. Q_vel로 조절 가능하나 유지(공격중 NIS와 tradeoff).

**축의존 (결과성=축별성분):** 단일축δ0.8 roll49°=추락 / 동시축δ0.8 26°/25°=생존. 학습은 방향 랜덤이라 자연히 혼합.

## Aliasing → RL 노이즈 → RHUKF 비교 (기여 논리)
자연 POMDP 노이즈 = ① 기동 aliasing(가감속·급기동, waypoint 코너 5×) ② vel↔바람 겹침(ws≥10, d′2.2) ③ 간헐 복귀 애매(OFF-gap) ④ 약공격 경계(δ0.1, gyro 1.78↔바람1.44).
+ RL 자체 노이즈(exploration, target bootstrap, heavy-tailed reward).
→ **이 노이지 학습신호에서 RHUKF-FV(2차, robust)가 Adam보다 (a)강건 정책 (b)적은 샘플로 수렴** = 본 기여.
⚠ Q는 탐지/복귀 기준(①공격 ②감쇠 ③바닥 ④d′)으로 **원칙적으로** 고정 — RHUKF 유리하게 노이즈 조작 금지(cherry-pick 반칙).

## ✅ 전 측정 완료 (2026-08-23)
- Q_gyro sweep → **2e-3 확정** (aliasing 봉우리, 1e-2 vel d′ 붕괴)
- Q_vel → **5e-3 확정** (POMDP 유지, 감쇠는 물리)
- dhover → **조건③ 확인** (δ0.8 track추락 ∧ dhover d≤8 생존)
- 3조건(결과성·탐지가능·대응가능) 전부 성립. **프레임워크 완전 확정.** → 본실험(RHUKF vs Adam·SGD·EKF).

---


# Ⅶ. ★★ POMDP 환경 재설계 (2026-08-24) — 옵티마이저 비교를 위한 난이도 확보

## 왜 (문제 발견)
Adam OFAT(lr3e-4/1e-3 × amsgrad × obs정규화 × net) 학습 결과 **모든 config가 ep20부터 포화**(생존1.0·지연1.0·정탐0.75 고정), 학습 reward도 ep75에 130-150 수렴. 원인 진단:
1. **eval 시나리오가 옛 고정값**(loe_combined 1.34-1.40 Nm, 무풍·비버스트·강공격) → 확정 tilt·연속δ·burst 아님.
2. **★ gyro가 trivial**: 강공격은 gyro 즉시 포화(d′9) → agent가 gyro만 봐도 충분 → vel(어려운 채널) 무시 → 즉시수렴 → **옵티마이저 차이 안 남**.
→ 샘플효율/강건성을 보이려면 **task가 진짜 POMDP**여야 하는데, gyro가 너무 깨끗해서 마스킹됨.

## 설계 원리 (커플링 깨기)
결과성 ∝ 공격크기 ∝ gyro탐지가능성 (강=결과성+쉬움 / 약=무해+애매). **"결과성 있으면서 탐지 어려운" 지점**을 커플링이 막음.
→ **NIS 바닥을 올려** 커플링을 깬다: 공격크기 그대로(결과성 유지)인데 바닥 대비 상대탐지난이도만↑. **에피마다 랜덤**이면 절대임계 불가 = 진짜 POMDP + 강건성 무대.

## ★ 오프라인 탐색 (zu_log 재구동, 다방법)
z/u 로깅(--log-zu) → UKF 오프라인 재구동(모델오차·Q/R 변경). 여러 메커니즘의 바닥상승 효과:
```
메커니즘         바닥gyro(base 0.49)   판정
mass 5-10%       0.49 (무효)          곱셈오차라 호버 u≈0서 0
I 20%            0.44 (무효)          호버 ω≈0
drag 40%         0.49 (무효)          호버 정지
gyro센서노이즈 x2-3  0.49-0.51 (미미)
★COM 토크바이어스   0.49→1.20(0.10)→1.46(0.15)  ← 유일하게 효과적
vel노이즈 0.4      vel 0.37→0.71        vel 채널용
```
**COM 바이어스가 유일한 레버.** 메커니즘: 플랜트 COM오프셋 → PX4 트림 → UKF가 트림명령을 "실제 회전"으로 오해 → 상시 gyro 잔차. mass/I/drag는 곱셈·상태의존이라 호버(u≈0,ω≈0)서 무효.

## ★ Sweet spot: COM ~0.10 N·m
```
COM 0.10 → gyro 바닥 1.20 → 약공격(δ0.1, gyro 1.78) gap 0.58 = 묻힘(POMDP)
                          → 중강공격(gyro 2.6-3.0) gap 1.3-1.8 = 탐지유지
COM 0.10 = COM오프셋 ~7.7mm (Iris 실제 6.7mm) = 배터리/페이로드 변동으로 현실적
+ GPS vel노이즈 0.3 → vel 바닥 0.59 (vel 약공격도 묻힘)
```
= **약공격만 POMDP화, 중강은 탐지유지.** sim2real 원칙("실기서 못 맞추는 미세항은 sim서도 안 맞춤") 정합 — COM은 배터리마다 달라 못 맞춤.

## 확정 설계 (구현 대상)
```
플랜트: 에피마다 랜덤 COM 토크오프셋 τ_com ~ ±0.10 N·m (roll/pitch, 부호·크기 랜덤)
        = 배터리/페이로드 COM 변동. PX4가 트림.
UKF:   COM 미모델링(고정 nominal) → 트림을 오해 → 바닥↑·에피마다 변동
       + GPS vel 센서노이즈 ↑(0.3) → vel 바닥↑
효과:  약공격 POMDP화(바닥에 묻힘) + 바닥이 에피마다 다름(절대임계 불가)
       = 시간패턴+양채널 융합 필수 = 진짜 online RL POMDP
       = 변동바닥 노이즈 견디는 옵티마이저(RHUKF) 우위 = 강건성 무대
```
공격은 여전히 물리적 결과성(드리프트/추락, 추락은 bootstrap). 온셋=바닥 위 step, 오프셋 빠름(바닥 상수).
도구: `etc/scripts/{offline_pomdp_explore.py, offline_cerr_qr.py}` (오프라인 재구동).

## [2][3][4] 구현 + 온라인 확인 (2026-08-24)
- **[2] 구현**: `online_rl_main.py` env `COM_BIAS_STD=0.10`(에피별 τ_com~U(±0.10)N·m roll/pitch, UKF u에 가산=미모델링) + `UKF_VEL_NOISE=0.3`(z vel 가산). 플랜트 불변(공격 GT 깨끗). 에피리셋마다 com_bias 재샘플.
- **[3] eval 교체**: `swrl_config.__post_init__`에서 확정 tilt분포 12개 재생성 — 평시(무풍/강풍)·약δ0.15·중δ0.4·강δ0.7 × {aggressive,circle} × 바람. 난이도별 분리평가.
- **[4] 파일럿 온라인 확인**: COM0.10+velN0.3 → **평시 gyro NIS 0.6~1.07**(baseline 0.4-0.5서 상승 확인). 바닥 상승 = 약공격 묻힘 조건 성립. 학습 climb·난이도별 분리는 300ep 후 판정.
- 미결: 온라인 바닥(0.8)이 offline예측(1.2)보다 낮음 → COM_BIAS 상향(0.12-0.15) 검토 여지. 파일럿 eval 곡선으로 판정.

## ★ 기동 aliasing 재발견 (2026-08-24) — POMDP의 진짜 메커니즘
COM 상수바닥은 "획일적 바닥↑"이라 원웅님 의도(급기동·바람이 동적 aliasing 유발)와 달랐다. 재조사:
**SPEED_MOD_AMP=0.5(가감속) + 급기동 + 바람 캡처 → 오프라인 분석:**
```
평시(공격X) gyro NIS를 기동강도 |ω|별로:
  gentle|ω|<0.5:  중앙0.40 90p0.60      중간0.5-1.5: 중앙0.60 90p0.99 max3.0
  급기동|ω|>1.5:   중앙1.05 90p2.35 max2.94  ← 공격(2.73)과 겹침!
```
= **가감속·급기동 순간 gyro가 공격 수준까지 튄다(동적 aliasing).** SPEED_MOD off가 기존 "gyro clean"의 원인이었음.
**지속성**: 기동aliasing run ~12스텝 vs burst공격 5-20스텝 = 겹침 → 단순 지속성으론 구분 불가 → 시간패턴+vel 통합 필요 = 진짜 POMDP.
**I오차 무효**(0/15/30% 동일) — aliasing은 관성 아니라 가감속·모터지연 과도에서 옴.
**환경 확정**: SPEED_MOD_AMP 0.5 + 회전바람 + COM_BIAS 0.05(보조). gyro가 급기동/바람 순간 애매 → 옵티마이저가 시간패턴 학습 = 샘플효율/강건성 무대.
도구 `etc/scripts/offline_maneuver_aliasing.py`.

## ⚠ 정정 (2026-08-24) — vel noise 제거 + 가감속은 기존 모드
1. **UKF_VEL_NOISE 제거**: sim이 이미 실기 GPS 노이즈 주입 중(run_sim.py:854 gps_noise×0.27=실기0.30×0.9, gyro σ [.066,.070,.044], 2026-08-20 sim2real 정합). UKF는 이미 실기수준 노이즈 측정을 받음. 임의 0.3 추가=실기 2배(비현실적) → 제거. **센서노이즈=sim2real 정합값이지 POMDP knob 아님.**
2. **가감속(SPEED_MOD)은 신규 아님**: 2026-08-21 추가된 기존 등속/가감속 모드(기본 off). "gyro clean" 진단이 등속 상태였던 게 원인 — 가감속 on이 aliasing 유발. 이건 궤적 프레임워크의 현실적 주행조건(등속만 나는 드론 없음).
3. **센서 구조 확인**: PX4 제어는 EKF2(자체 융합)로 안정 비행, UKF(탐지)는 실기노이즈 z 받음 → NIS 바닥 현실적. 이게 이미 된 설계.
→ **확정 POMDP 환경 = 가감속 on(aliasing) + COM_BIAS 0.05(변동바닥) + sim2real 센서노이즈(기존). vel noise 추가 안 함.**

## ★ POMDP aliasing 재확인 (2026-08-24, 정정환경 + burst 공격)
> ⚠⚠ **2026-08-26 정정: 아래 "급기동 중앙 2.32 / 90p 2.97" 은 평시 표본에 공격 종료 직후 잔향이
> 섞인 오염값이다.** 평시에서 tail 15스텝을 배제하면 1.09 / 1.97 로 내려간다. 상세는 **Ⅷ-7**.
> 이 블록의 aliasing 수치는 인용 금지 — Ⅷ 을 볼 것.
정정환경(가감속on + COM0.05 + 기존 센서노이즈, vel노이즈 X) + burst 공격(PROB_CONSTANT=0)으로 재캡처·분석:
```
평시 gyro: 전체 0.48 / 급기동(|ω|>1.5) 중앙 2.32 90p 2.97  ← 공격(2.67) 수준까지 튐
급기동 빈도: 14% (가감속으로 빈번, 이전 등속 2%→14%)
★지속성: burst공격 run 12-29스텝 / 기동aliasing run 16스텝 → 겹침!
   (이전 지속공격 887스텝은 aliasing 12스텝과 쉽게 구분됐음)
```
= 짧은 burst 공격이 기동 aliasing과 (a)순간NIS 2.3-3.0 (b)run길이 12-16 둘 다 겹침 → 구분불가 = 진짜 POMDP.
공격은 "반복+vel동반+맥락"으로만 구분 → 시간패턴 학습 = 옵티마이저 샘플효율/강건성 무대.
GPS 속도노이즈 확인: run_sim.py:872 vel σ 0.079/0.069/0.219 (실기×0.9) 주입됨 = UKF vel 측정 현실적.
도구 `plot_aliasing_timeseries.py`(경로인자), `PROB_CONSTANT_ATK` env(burst강제).

## POMDP 환경 확정 + Adam 학습 시작 (2026-08-24)
난이도 철학(필터 벤치마크가 강외란으로 EKF/UKF 가르듯, 노이지 POMDP로 Adam/RHUKF 가름) 확정.
**확정 환경**: 가감속(SPEED_MOD 0.7) + Q_gyro 5e-3(공격 2.7→2.2↓+offset빠름) + COM_BIAS 0.05 + 회전바람 + burst(30%상수). vel노이즈 X.
**검증**(zu_v2, 순수기동 오염제거): gentle 0.30 / 순수기동 90p 1.86 / 공격 2.20 → 겹침(POMDP). 약공격은 더 겹침.
**교훈**: gyro를 강공격까지 애매화 불가(물리). POMDP는 판단(약공격 애매+복귀타이밍+기동FP)에 있음. 강공격은 easy anchor 수용.
→ Adam 300ep 학습(results_pomdp_adam): 학습곡선 climb 여부가 난이도 적절성 판정. climb생기면→RHUKF 비교, 즉시포화면→난이도↑.

## ★ Adam vs RHUKF 첫 비교 (2026-08-24, POMDP 환경, 단일 seed)
POMDP 환경(가감속0.7+Q5e-3+COM0.05+바람+burst, F1 climb 0→0.6=non-trivial)서 Adam·RHUKF 각 300ep:
```
              Adam    RHUKF    판정
샘플효율(F1 0.5)  ep36   ep24     RHUKF 빠름(sample efficiency)
reward(최종50)   140    164      RHUKF 높음(RL 목표)
FP율            0.055  0.045    RHUKF 낮음
지연            2.4    2.1      RHUKF 빠름
최종 F1         0.581  0.496    Adam 높음
F1 분산         0.430  0.450    비슷(둘 다 큼)
```
**해석**: RHUKF가 4/5 지표(샘플효율·reward·FP·지연) 우세, F1만 Adam. 두 옵티마이저가 **다른 정책 수렴**(RHUKF=보수적 저FP저recall, Adam=공격적 고recall고FP). RHUKF가 RL 목표(reward)를 더 잘 최적화.
⚠ **단일 seed·F1 분산 0.43 → 결정 불가.** 다중 seed(3+) 필요.
plot `adam_vs_rhukf_curves.png`. exkurt 32-37(heavy-tailed) = RHUKF 유리 조건 확인.
---


# Ⅷ. ★★ Perceptual Aliasing 정밀 측정 (2026-08-26) — POMDP 난이도가 "어디에" 있는지 확정

> **한 줄 결론**: 확정 프레임워크에서 **gyro 의 진폭 aliasing 은 사실상 없다**(평시 aliasing율 0.02~0.28%,
> 정상상태 Bayes 오류 0.001~0.020). Perceptual aliasing 의 본체는 **진폭이 아니라 타이밍**이다 —
> ① 온셋 0~2스텝(정보 부재) ② 종료 後 vel 잔향 2~4초 ③ vel 채널의 상시 겹침(약공격서 AUC 0.50=우연).
> ⚠ **Ⅶ의 "급기동 gyro 중앙 2.32 = 공격 수준" 기록은 평시 표본에 공격 종료 직후 잔향이 섞인 오염이었다**(아래 Ⅷ-7).

## Ⅷ-0. 방법 (재현 가능)
**데이터 2종** — 둘 다 확정 env(가감속 0.7 · 회전바람 arm 0.02 · COM ±0.05 · burst · Q_gyro 5e-3):
| | 출처 | 규모 | 쓰임 |
|---|---|---|---|
| **A** | `results_zu_v2/zu_log.npz` 오프라인 UKF 재구동 | 15에피 14,788행(50Hz) → 2,963 관측(10Hz) | 시간구조·요인분해·Q A/B (버스트 경과 `atk_delay` 라벨 보유) |
| **B** | `results_tune_*/train.log` 4런 파싱 | 91,524스텝 (δ~U(0.1,0.8) 전구간) | δ 의존·조건별 바닥 (표본 대량) |

**클래스 정의 (오염 제거가 핵심)**
```
공격 정상상태 : 버스트 온셋 후 ≥3스텝  (관측이 완전히 실린 상태)
공격 온셋     : 온셋 후 0~2스텝        (관측에 아직 정보 없음)
평시(순수)    : 공격 아님 ∧ 직전 버스트 종료 후 >15스텝(A) / >20스텝(B)
복귀 tail     : 공격 아님 ∧ 종료 후 ≤15스텝  ← 이걸 평시로 세면 측정이 깨진다
```
TRACK 스텝만 사용(HOVER 는 기동이 없어 aliasing 이 소멸 + 공격 중 HOVER 비율 69~88% 라 편향).

**지표**: d′(분리도) · AUC · **OVL**(분포 겹침질량, 1=완전 aliasing) · **Bayes 오류**(균형사전 1스텝 최적판정)
· **애매질량**(사후확률 P(공격|관측)∈[0.3,0.7] 표본비율) · **aliasing율**(평시인데 공격 하위10% 선을 넘은 비율).
도구: `etc/scripts/alias_{core,parse_trainlog,measure_timing,measure_conditions,measure_delta,plot_timeseries,plot_summary}.py`
그림: `alias_fig1_timeseries.png` · `alias_fig2_event_profile.png` · `alias_fig3_summary.png`

## Ⅷ-1. ★ 시간구조 — 공격은 즉시 보이지 않고, 끝나도 즉시 사라지지 않는다 (A, δ0.35~0.51)
```
 온셋 이후 경과      n  | gyro 중앙  90p | vel 중앙  90p
   0~2스텝 (0.0-0.2s) 64 |   0.76  2.04 |  0.58  1.08   ← 평시와 구분 불가
   3~4스텝 (0.3s)     52 |   1.99  2.39 |  0.67  1.20   ← 상승
   5~9스텝 (0.5s)    126 |   2.43  2.82 |  0.76  1.19   ← 포화
  10~19스텝(1.0s)    104 |   2.52  3.00 |  0.75  1.12
  [순수 평시]        2405 |   0.44  0.75 |  0.37  0.73
```
→ **gyro 는 온셋 후 3스텝(0.3s) 지나야 오른다.** 0~2스텝은 원리적으로 판정 불가 = **탐지지연의 물리적 하한**.
   프레임워크의 대응 데드라인 d≤3 은 이 하한과 정확히 맞닿아 있다(여유 0).
```
 종료 이후 경과      n  | gyro 중앙 | vel 중앙
   1~2스텝            33 |   2.57   |  0.70     ← 공격 끝났는데 관측은 최고치
   3~5스텝            38 |   1.97   |  0.67
   6~10스텝           71 |   1.87   |  0.80
  11~20스텝          138 |   1.03   |  0.81
  21~40스텝          201 |   0.55   |  0.68
  41+스텝             75 |   0.56   |  0.72
```
→ **gyro 는 2~5스텝에 복귀, vel 은 20~40스텝(2~4초) 끌린다.** burst OFF 간격이 10~30스텝이므로
   **OFF 구간 대부분이 vel 상으로는 아직 "공격 중"으로 보인다** = 복귀 판정의 비대칭 aliasing.

**상태별 분리도 (A, 순수평시 기준)**
| 비교 | d′ | AUC | OVL | Bayes오류 | 애매질량 |
|---|---|---|---|---|---|
| gyro 정상상태 | **3.76** | 0.992 | 0.072 | **0.034** | 0.052 |
| gyro 온셋0~2 | 1.02 | 0.754 | 0.492 | **0.244** | 0.317 |
| gyro 복귀tail | 2.51 | 0.961 | 0.185 | 0.093 | 0.098 |
| vel 정상상태 | 1.21 | 0.817 | 0.495 | **0.245** | 0.417 |
| vel 온셋0~2 | 0.91 | 0.756 | 0.577 | 0.278 | 0.532 |
| vel 복귀tail | 1.33 | 0.833 | 0.458 | 0.226 | 0.347 |

## Ⅷ-2. 공격 세기 δ 별 aliasing (B, 91,524스텝, 온셋·tail 오염 제거)
```
 δ 구간          n  | gyro d′   AUC   OVL  BErr  중앙 | vel d′   AUC   OVL  BErr  중앙 | 2D BErr
 0.10-0.20     391 |   4.11  0.997 0.042 0.020 1.26 |  0.07  0.500 0.925 0.443 0.37 |  0.017
 0.20-0.30     168 |   7.68  1.000 0.011 0.003 2.02 |  0.36  0.595 0.837 0.404 0.44 |  0.001
 0.30-0.45     453 |   9.73  0.999 0.012 0.006 2.38 |  0.58  0.663 0.723 0.363 0.50 |  0.005
 0.45-0.60     359 |  13.70  1.000 0.003 0.001 2.81 |  1.21  0.795 0.520 0.258 0.76 |  0.000
 0.60-0.80     551 |  15.70  1.000 0.004 0.002 3.00 |  1.82  0.894 0.352 0.175 0.86 |  0.002
 [평시 TRACK] 29287 | gyro 중앙 0.41 90p 0.64 99p 0.95 | vel 중앙 0.38 90p 0.68 99p 1.05
```
- **gyro 는 δ0.1(최약)에서도 정상상태면 거의 완전 분리**(d′ 4.11, BErr 0.020). "약공격이 gyro 에 묻힌다"는 성립하지 않는다.
- **vel 은 δ<0.3 에서 AUC 0.50 = 완전 우연.** 약공격에 대해 vel 채널은 정보가 0 이다.
- ⚠ 이 표는 **정상상태**만 본 값이다. 실제 에피소드의 공격 스텝 중 정상상태 비율은 낮다(버스트 5~20스텝 중 앞 3스텝이 온셋).

## Ⅷ-3. 회전바람(arm=0.02)의 기여 — 실측 (B, TRACK, 순수평시)
```
 조건            n     | 중앙   90p   99p   max | aliasing율 (판정선 1.23)
 무풍   0-0.5   4085   | 0.38  0.55  0.67  1.29 |  0.02%
 약풍   0.5-2  12665   | 0.37  0.56  0.80  1.40 |  0.06%
 중풍   2-4      443   | 0.43  0.55  0.90  1.17 |  0.00%
 강풍   4-7     2636   | 0.40  0.62  0.89  1.95 |  0.23%
 최강풍 7-10    9458   | 0.49  0.78  1.04  1.61 |  0.20%
```
→ 회전바람은 평시 gyro 바닥을 **중앙 0.37→0.49 (+32%), 90p 0.56→0.78 (+39%)** 로 확실히 올리고
  aliasing율을 **0.06%→0.20% (3배)** 로 키운다. **효과는 실재하지만 공격(중앙 1.26~3.00)에 닿지 못한다.**
  회전 모멘트를 만든 설계는 의도대로 작동했으나, arm 0.02 는 gyro 를 애매화할 만한 크기가 아니다.

## Ⅷ-4. 궤적(급기동·가감속)의 기여 — 실측
```
 궤적          n      | 중앙   90p   99p   max | aliasing율
 circle       7332    | 0.41  0.67  0.93  1.35 |  0.05%
 figure8      3809    | 0.39  0.58  0.85  1.34 |  0.03%
 waypoint     5461    | 0.41  0.63  0.97  1.43 |  0.18%   ← 코너 급전환
 aggressive  12685    | 0.42  0.66  0.97  1.95 |  0.15%
 최강풍×aggressive 4608 | 0.50  0.79  1.05  1.61 |  0.28%   ← 최악조합
```
**A 에서 기동강도별 (판정선 1.31):**
```
 |ω| 0.0-0.3  n=1537 | 중앙 0.41 max 1.25 | aliasing  0.0%
 |ω| 0.3-0.6  n= 507 | 중앙 0.50 max 1.46 | aliasing  0.4%
 |ω| 0.6-1.0  n= 275 | 중앙 0.55 max 1.42 | aliasing  0.4%
 |ω| 1.0-1.5  n=  59 | 중앙 0.82 max 1.78 | aliasing 16.9%   ← 여기서만 튄다
 |ω| >1.5     n=  27 | 중앙 1.07 max 1.69 | aliasing 25.9%
 |a_xy| >20 m/s² n=27 | 중앙 0.68 max 1.48 | aliasing 11.1%
```
→ **급기동 구간(|ω|>1.0)에서는 실제로 17~26% aliasing 이 난다. 다만 그 구간이 전체의 3.6% 뿐이다.**
  가감속(|a|)은 |a|>20 m/s² 극단에서만 기여(11%, 표본 1.1%).

**요인분해 (평시 gyro NIS 선형회귀, 표준화 계수):**
```
 |ω| 회전강도  β=+0.516  (단독 R² 0.312)   ← 지배 요인
 ws  회전바람  β=+0.149  (단독 R² 0.075)
 |ω̇| 급기동   β=+0.012  (단독 R² 0.064)
 |a| 가감속    β=+0.025  (단독 R² 0.013)
 전체 R² = 0.335   (나머지 2/3 는 COM·모터지연·센서노이즈 등)
```
→ **sharpness(|ω̇|)·가감속(|a|)보다 "얼마나 돌고 있나(|ω|)"가 압도적.** 가감속 노브는 |ω| 를 키우는 경로로만 기여한다.

## Ⅷ-5. Q_gyro 가 aliasing 의 지배 노브 (A, 동일 데이터 재구동 A/B)
```
 Q_gyro | 평시중앙  90p   99p   max | 급기동|ω|>1 중앙  max | 공격중앙 |  d′   BErr  aliasing율
  1e-3  |  0.77  1.26  2.42  3.00 |    1.22   3.00 |  2.73 | 3.52 0.060  4.66%
  2e-3  |  0.61  0.98  1.90  2.49 |    1.08   2.49 |  2.52 | 3.74 0.043  2.58%   ← 문서 Ⅵ 확정값
  5e-3  |  0.44  0.75  1.26  1.78 |    0.92   1.78 |  2.29 | 3.76 0.034  0.83%   ← 실제 사용값(Ⅶ·밤샘배치)
  1e-2  |  0.35  0.64  1.14  1.72 |    0.82   1.72 |  2.08 | 3.72 0.035  1.16%
```
→ ⚠ **Ⅵ(2e-3)과 Ⅶ/실제 학습(5e-3)이 어긋나 있었다.** 5e-3 은 2e-3 대비 aliasing율을 **2.58%→0.83% (1/3)** 로 줄인다.
  즉 POMDP 난이도를 위해 만든 기동 aliasing 의 상당 부분을 Q 상향이 되돌려버렸다. **Q_gyro 를 단일 값으로 확정 기록할 것.**

## Ⅷ-6. COM 바이어스(±0.05 N·m)의 기여 — 미미
```
 설정              평시gyro중앙  90p  공격중앙 |  d′   OVL   BErr  aliasing율
 COM 0 (미주입)        0.32     0.68   2.30  | 4.11 0.065 0.033   0.8%
 COM ±0.05 (확정)      0.44     0.75   2.29  | 3.76 0.072 0.034   0.8%
```
→ 바닥을 0.32→0.44 로 올리지만 **분리도·aliasing율은 사실상 불변**. 08-24 오프라인 예측(COM0.10→바닥1.20)과 달리
  0.05 에서는 POMDP 레버로 기능하지 않는다.

## Ⅷ-7. ★★ 정정 — Ⅶ의 "기동 aliasing" 기록은 tail 오염이었다
Ⅶ 은 *"급기동(|ω|>1.5) gyro 중앙 2.32 / 90p 2.97 → 공격(2.67) 수준까지 튐"* 이라 기록했다.
동일 데이터(zu_v2)·동일 Q(2e-3)로 **평시 정의만 바꿔** 재측정:
```
 평시 표본 정의                 |ω|>1.5  n   중앙   90p
 tail 미배제 (구 분석 방식)             65  2.43  3.00   ← 구 기록 재현됨
 tail 15스텝 배제 (본 분석)             27  1.09  1.97
 tail 30스텝 배제                      20  0.90  1.49
```
→ **"평시 급기동" 표본의 58%(65→27)가 실은 공격 버스트 종료 직후 잔향이었다.**
  물리적으로 당연하다: 공격이 끝난 직후가 곧 기체가 자세를 되찾으려 크게 도는 구간이라
  **|ω| 가 큰 평시 표본 = 공격 직후 표본**으로 자동 정렬된다.
  ⇒ **기동 자체가 공격을 흉내내는 것이 아니라, 공격의 잔향이 기동으로 오분류된 것.**
  Ⅶ 의 "aliasing 봉우리로 Q=2e-3 확정" 근거(0.689)도 같은 오염 위에 있으므로 재검토 대상.

## Ⅷ-8. 종합 판정 — POMDP 난이도는 어디에 있나
| 원천 | 실측 크기 | 판정 |
|---|---|---|
| **온셋 0~2스텝 정보 부재** | Bayes오류 0.244 (gyro) | ★ 최대 원천. 물리적 하한이라 제거 불가 |
| **종료 後 vel 잔향 2~4초** | OFF구간 10~30스텝 대부분을 덮음 | ★ 복귀 판정을 애매하게 만드는 본체 |
| **vel 채널 상시 겹침** | δ<0.3 AUC 0.500(우연), 전체 BErr 0.245 | ★ 지속적 POMDP 채널 |
| 급기동 |ω|>1.0 순간 | aliasing 17~26%, 그러나 표본 3.6% | 부차 |
| 회전바람 arm0.02 | 바닥 +32%, aliasing 0.06→0.20% | 부차(작동은 함) |
| COM ±0.05 | 바닥 +0.12, 분리도 불변 | 사실상 무효 |
| **gyro 진폭(정상상태)** | BErr 0.001~0.020 | **aliasing 없음 = easy anchor** |

**서사 정정**: "기동·바람이 gyro 를 공격 수준까지 튀게 해서 POMDP" 는 실측으로 지지되지 않는다.
성립하는 서사는 **"gyro 진폭은 쉽지만, 언제 시작했고 언제 끝났는지가 어렵다"** —
즉 난이도가 **탐지(detection)가 아니라 stopping(온셋·복귀 시점 판정)** 에 있다.
이는 오히려 본 과제 프레이밍(양방향 stopping-time POMDP)과 **더 잘 맞는다**.
CUSUM 이 burst 에서 붕괴(지연 24스텝·미탐 16%)하는 것도 같은 이유로 재해석된다.

## Ⅷ-9. 미결 / 다음
1. **Q_gyro 단일 확정** — Ⅵ(2e-3) vs 실제(5e-3) 불일치 해소. tail 오염을 제거한 상태에서 재판정할 것.
2. **온셋 표본 확대** — 온셋 0~2스텝 표본이 A 에서 64개뿐. 온셋 구간만 조밀 캡처(δ 층화)해 Bayes 오류 신뢰구간 확보.
3. **δ0.1~0.3 × 온셋** 결합 조건이 진짜 최악 지점 — 현재 표본 부족. 전용 캡처 필요.
4. aliasing 을 키우려면 레버는 **Q_gyro 하향(5e-3→2e-3)** 또는 **arm 상향**이지, COM 이 아니다.
   단 ⚠ 노이즈를 RHUKF 유리하게 조작하는 것은 반칙 — Ⅵ 의 원칙(탐지/복귀 기준으로 Q 고정) 유지.

---


# Ⅸ. ★★ config E 검증 + 기동 재정합 (2026-08-27)

> Ⅷ("aliasing 은 타이밍·gyro 진폭은 자명")을 받아 Q·R 전수 스윕 → **config E 후보 확정·검증 완료.**
> 그림: `configE_facet_timeseries.png`(15에피 전수) · `timewin_E_timeseries.png`(시간창 시나리오) ·
> `qr_sweep_summary.png`(노브 지형) · `before_after_timeseries.png`. 아티팩트 09장에 동일 내용.

## Ⅸ-1. Q·R 노브 지형 (오프라인 zu 재구동, OFAT 1e-4~5e-2 + 2D 격자 36조합)
- **gyro 채널은 Q_gyro·R_gyro 둘만 유효** — 각속도 전파식에 pos/vel/euler 가 안 들어감(구조적 분리).
  vel 채널은 R_vel·Q_euler 지배. **Q_pos·R_pos 양채널 완전 무효.**
- ★ **"고집=R↑" 전제는 반만 맞다.** 공격이 z 가 아니라 **u 로** 들어오므로 R↓로 측정을 더 믿어도
  잔차는 남는다(R_gyro 40배↓에도 sustain 1.06→0.98 불변). ⇒ **R↓ = 고집 유지 + 자명함만 깎는 공짜 방향.**
- 도구: `etc/scripts/qr_{ofat_sweep,grid2d,candidates,plot}.py`. env 노브 7종 노출
  (`UKF_Q_POS/EULER/VEL/GYRO`, `UKF_R_POS/VEL/GYRO`) + **구 UKF_R_VEL 이 gyro 블록(R[6:9])에 쓰던 버그 수정**
  (사용 스크립트 없어 과거 실험 무오염. 백업 `env/ukf_filter.py.bak_pre_qr_knobs`).

## Ⅸ-2. config E (검증 완료 · 기본값 반영은 결정 대기)
```
        Q_gyro   R_gyro  R_vel  Q_euler          A 현행    →    E
config  2e-2     0.02    0.01   2e-3
① 고집 (공격 후반/초반)                            1.36          1.20 유지
② τon                                          3             3   유지
③ τoff gyro/vel                                8/44          7/18
④ gyro SNR / BErr / alias                      7.74/0.019/0.6%   3.86/0.103/11.1%
④ vel  SNR / BErr                              0.80/0.353    0.23/0.443
   공격 고원                                     2.35          1.84 (살아있음)
δ별 묻힘: A 전구간 0% → E δ0.1-0.25 49% / 0.25-0.55 3-4% / 0.55-0.8 0%
```
= **약공격만 POMDP 화, 강공격 easy anchor 유지, 같은 δ0.4 도 맥락(패턴·바람) 따라 7~14% 요동 = 절대임계 불가.**

## Ⅸ-3. 시간창 시나리오 (clean→강풍 ws8→겹침→공격만→복귀, 4패턴×δ{0.4,0.7}, 전셀 완주)
```
구간            δ0.4 g/v      δ0.7 g/v
① clean        0.31/0.63     0.34/0.59
② 바람만        0.43/0.75     0.44/0.75
③ 바람+공격      1.99/0.79     2.49/0.83
④ 공격만        1.99/0.67     2.49/0.69   ← 바람 꺼져도 잔차 유지 = 고집
⑤ 복귀          0.33/0.67     0.36/0.70
전이(δ0.7): 공격ON 0.43→2.36(3스텝) / 바람OFF 중 2.47→2.49(불변) / 공격OFF 2.40→0.74(3-6스텝)→0.39
δ0.4 vs 0.7 고원 1.99 vs 2.49 = 계조 살아있음 (A 는 둘 다 3.0 포화)
```

## Ⅸ-4. aggressive 가 조용했던 이유 (질문 답 + 버그 수정)
① **구조**: 4-phase 중 절반이 제자리 수직왕복(|ω|≈0), 반원도 코너 없는 등속 선회.
   스파이크 원천은 waypoint 코너(방향 불연속) — 08-21 진단("회전적으로 gentle")과 일치.
② **버그**: 08-26 궤적축소 때 agg_radius 2.24→1.28 만 줄이고 Tp(agg_phase_s 5.0)를 안 줄여
   반원속도 Ra·π/Tp 1.41→0.80 로 감속. → **수정: agg_phase_s 3.35** (반원 1.20 m/s=circle 동일,
   선회 0.94 rad/s>circle 0.75). ⚠ 그림 10·11은 수정 전 캡처.

## Ⅸ-5. 방향 확정 (사용자 결정 2026-08-27)
- **δ~U(0.1,0.8) 유지.** 결과성 재측정: 궤적이탈 δ0.3-0.4 배수<1(완전보상)·δ0.6 시작·0.8 확실.
  그러나 기여 = "탐지=위협"이 아니라 **노이지 POMDP 옵티마이저 비교** → 약공격의 애매함(49% 묻힘)이
  곧 무대. 호버 = 공격불가지론적 fallback ("보상되는 공격이라도 감지하면 호버"가 정합).
- 버스트 U(5,20)·속도상한 2.0 유지(실기 안전). 기동수정(시간워프 편향·FREQ1.0·R1.6/ω0.75) 유지 —
  **가감속 중에도 실기 속도 봉투(MPC_ACC_HOR 3.0·JERK 8.0) 안에서 현실적으로 난다.**
- 코드 반영: 기동 4건 + UKF 노브·버그 = 반영 / **config E 기본값 = 검증 완료·채택 결정 대기.**

---


# Ⅹ. ★★ 대응·복귀 문법 확정 + 결과성 재정의 (2026-08-27 오후)

> 근거 데이터: results_hold_* (홀드모드 스윕) · results_v3_* (풀시퀀스 검증) · results_t07 ·
> results_final_delta (최종 δ-스윕). 아티팩트 09장 동기 반영.

## Ⅹ-1. 07-23 "사수→flip" 재검 — 뒤집힘
현 플랜트(질량·C_torque·모터지연 정합)에서 완전 사수 홀드도 flip 없음: δ0.8 에서 u_norm 23,
roll 최대 47.6° < 한계 60.2°. **roll 피크는 홀드 방식과 무관하게 동일(47~48°)** = 자세 위험은
전부 온셋 과도에서 오고 복원력 세기와 무관 → "복원력 vs flip" 트레이드는 애초에 없었다.
→ soft-hold(복원력 0, 42m 활강) 폐기, **강제 홀딩(사수)이 기본** (HOVER_EMAX 노브는 탈출구).

## Ⅹ-2. 위치 격리(containment) 문턱 실측
```
δ0.6: 1.7m 밀림 → 0.6m 복귀·유지     δ0.7: 4.0m 격리, 종료 즉시 재진입
δ0.8: 32~36m — 격리 불가 (표류 3~4 m/s > 위치루프 권한 2.0 m/s)
```
문턱 ∈ (0.7, 0.8): 공격 토크가 위치 제어 권한을 초과하는 지점.

## Ⅹ-3. track = 임무 복귀 문법 (재접근) — 구현 확정
- 궤적 진행이 **위치 동기화**됨: reference 에서 2m 밖이면 시계 동결 + 동결점으로 감속 프로파일
  복귀 비행, 2m 안이면 진행 재개 (PX4 오토미션과 같은 "도달해야 넘어가는" 문법).
- 구형("시간표가 혼자 도망")은 임무 추종 의미론이 아니었음 — 공격에 밀리면 목표와의 격차가
  무한 확대 → drift 절단이라는 인공 결말을 만들었다.
- hover: 판정용 sp = 현재위치(판정 유예), 명령 sp = 앵커. 재접근 중 동일 + 60m 절대 안전망.
- RL 불변: 행동·관측·보상 그대로. 환경 메커니즘만 교체.

## Ⅹ-4. ★ 결과성 재정의 — "추락"에서 "임무 손실 스펙트럼"으로
- 구 δ0.8 의 track/hover "추락"은 **전부 crash_drift 판정 산물**(물리 추락 0건)이었다.
- 신문법 실측(공격 10s 창): δ0.7 무대응 track — 완주, 궤적오차 최대 2.0m, roll 32°.
  δ0.8 호버 — 32m 통제 표류 후 재접근 12s 만에 임무 재개 완주.
- ∴ 결과성 = **임무 정지 시간 + 궤적 오차 + (자세 여유 소모)** 의 연속 스펙트럼.
  호버 프레이밍은 CLAUDE.md 원 결정("공격불가지론적 fallback + 검증기동, recovery 아님")로 복귀.

## Ⅹ-5. 공격 밴드 최종 확정 = U(0.1, 0.7) — 양끝이 서로 다른 축
- **하한 0.1 = 탐지가능성 경계(관측)**: 약공격 애매성(δ0.1–0.25 의 49% 가 평시에 묻힘) = POMDP
  무대. 보안 프레이밍(침입 이벤트 식별)에서 무해 공격도 탐지 대상 — FN = "침입 미탐"으로 정당.
  결과성 재정의로 "하한을 결과성으로 정해야 한다"는 논거 자체가 소멸.
- **상한 0.7 = 대응유효성 경계(제어 권한)**: δ≳0.75 부터 위치 격리가 물리적으로 불가 =
  결과가 정책과 무관해지는 구간. 그 표본은 행동-결과 연결이 없어 학습 gradient 에 순수 노이즈.
  0.7 은 격리(≤4m)·자세여유(28°)·easy-anchor 탐지(고원 2.4+)가 모두 성립하는 최대 세기.
- 잃는 것(정직): "무대응=추락" 극적 대비 — 판정 인공물이었으므로 실손실 없음.

## Ⅹ-6. 부수 효과
- 호버 대응 경로에선 공격 종료 후 회복 잔향(구 τoff 15스텝)이 **0** — 종료 시점에 이미 자세가
  잡혀 있기 때문. "복귀가 느리다" 문제의 해법이 필터가 아니라 올바른 대응 그 자체였다.
- 재접근 덕에 복귀 구간(공격 후) 학습 데이터가 절단되지 않음 — 양방향 stopping 학습의 전제.

---


# Ⅺ. ★★ 호버 대응의 재정의 — "생존 구제"에서 "hijack 봉쇄"로 (2026-08-27 저녁)

> 원웅 지적: 기록된 "호버=구제(생존)" 주장이 중간에 바뀐 근거 위에 서 있는지 재검.
> 결론: **그렇다.** 생존-구제는 아티팩트였고, 정직한 대응 = hijack 봉쇄다.

## Ⅺ-1. 기록의 모순 (원웅이 감지한 지점)
```
RESULTS.md:364-365  "δ0.8 track추락 ∧ dhover 생존 → 조건③ 성립 → 프레임워크 완전 확정"
        ↓ Ⅹ장(오늘)
RESULTS.md:750      "구 δ0.8 track/hover 추락은 전부 crash_drift 판정 산물(물리 추락 0건)"
```
조건③("호버로 구제=생존")의 근거였던 "δ0.8 track 추락"이 crash_drift 판정 아티팩트였다.
roll 49°(구 기록)도 flip 한계 60° 미만 = 물리 추락 아님. **"호버가 추락을 막는다"는 버그 위의 주장.**

## Ⅺ-2. 생존-구제는 물리적으로 없다 — 3-way 증명
- **위치 유지 불가**: position hold 4.1m / 공격적 4× 3.2m / 자세-수평 홀드 112m(폭주).
  공격이 수평제어의 유일 수단(틸트)을 탈취 → 제어로 거부 불가. (results_poshold/atthold/hh*)
- **flip-구제 불가**: 최악조건(waypoint 코너+강풍ws8+COM0.10+δ0.7)에서도 track roll **31°** << 60°.
  호버 31~35°. **둘 다 flip 없음·생존.** (results_flip). 우리 밴드·속도제한 안에서 track은 안 죽는다.
- ∴ 밴드 ≤0.7 에서 track/호버 **생존 차이 0**. "호버가 추락 구제"는 폐기.

## Ⅺ-3. ★ 정직한 대응 = hijack 봉쇄 (FDI hijacking 프레이밍과 정합)
공격은 추락이 아니라 **궤적 탈취(FDI hijacking)**. 그러면 결과성도 hijack 그 자체:
```
공격    roll/pitch 토크 탈취 → 드론을 원치 않는 궤적으로 몰음
결과성  무대응 시 공격자가 임무 전역에 걸쳐 드론 조종 (추락 아님)
대응    탐지→호버 정지→공격자 조종 범위 봉쇄
```
**봉쇄 정량 (waypoint δ0.7, 공격 10s):**
```
          공격중 이동   위치 spread   커버 면적
  track     22.5 m        7.0 m       17.5 m²
  호버       9.1 m        4.3 m        3.1 m²   ← 면적 5.6×·이동 2.5× 축소
```
호버는 위치를 못 지키지만(4m 표류 불가피), **공격자가 드론을 끌고 다닐 수 있는 범위를 봉쇄**한다.

## Ⅺ-4. 프레임워크 3조건 재서술 (아티팩트/CLAUDE.md 반영 대상)
- ① **결과성**: 무대응 시 공격자가 궤적 hijack (임무 전역 조종·off-path) — 추락 아님
- ② **탐지가능성**: NIS 온셋 엣지 (gyro 5× 스파이크) — 불변
- ③ **대응가능성**: 탐지→호버로 hijack 봉쇄 (면적 5.6× 축소) + 임무 심화 차단 + 자세 안정화(기동틸트 제거)
     + 깨끗한 센싱(지속 탐지). **"생존"이 아니라 "봉쇄+탐지".**
- 호버 프레이밍: 위치방패 아님. **공격불가지론적 failsafe 정지 + hijack 봉쇄 + 검증기동.**
- 복귀: 최근접점 재접근(A) → 임무 재개.
- (선택) 지속공격 시 LAND 에스컬레이션 = 유일한 실효 완화.

## Ⅺ-5. 기여는 오히려 강해진다
"강건제어로 막으면 되지 왜 탐지+RL이냐?" → **막을 수 없어서**(3-way 증명). 공격이 제어권한을
탈취하므로 남는 유일한 대응 = 탐지 + 봉쇄된 정지. RHUKF-FV가 이 양방향 stopping 을 Adam보다
샘플효율 우위로 학습. **생존-구제라는 약한(그리고 거짓인) 주장을 버리고 hijack 봉쇄+탐지로 굳힌다.**

---


# Ⅻ. ★★ 한방향 burst hijack 결과성 실증 (2026-08-28) — 정확한 시나리오

> 정정: Ⅹ·Ⅺ의 호버 드리프트 분석은 **지속 공격(10s 연속)** 으로 했으나 실제 시나리오는 **burst**다.
> 지속 토크는 PX4 적분기가 상쇄해 hijack 이 잘 안 된다. **burst(짧은 ON)가 hijack 의 메커니즘**이고
> (적분기가 못 잡는 펄스 누적), 이는 CUSUM 붕괴와 같은 원리다. 아래는 burst 시나리오 실측.

## Ⅻ-1. 설계
- 고정 방향(+roll) burst, ON {10,20}스텝({1,2}s)/OFF 25(2.5s), 공격창 150~380(23s) → 5~6 버스트.
- δ {0.5, 0.7}, 패턴 {waypoint, aggressive}, 정책 {track(NAIVE·재접근OFF), whover2}.
- 측정: 공격구간 **순드리프트(끝−시작)** = 한방향 누적 hijack 정도. (results_burst_on1s / on2s)

## Ⅻ-2. 결과 — 무대응 hijack vs 호버 봉쇄
```
 ON  패턴        δ    track hijack   호버 봉쇄   봉쇄율
 1s  aggressive 0.5     2.4m         0.6m       75%
 1s  aggressive 0.7     2.7m         1.0m       63%
 1s  waypoint   0.5     5.0m         0.6m       87%
 1s  waypoint   0.7     4.3m         1.2m       72%
 2s  aggressive 0.5     1.9m         0.4m       79%
 2s  aggressive 0.7     2.5m         0.7m       72%
 2s  waypoint   0.5     4.5m         0.6m       87%
 2s  waypoint   0.7     4.7m         0.7m       85%
```
- **무대응 = 한방향 누적 표류(hijack) 1.9~5.0m** / **호버 = 0.4~1.2m 봉쇄 (63~87%).**
- **waypoint > aggressive**: 직선 구간이 body-roll 을 일관 수용해 누적 / aggressive 는 선회로 방향 상쇄
  (문서 "circle/wp 최취약, aggressive 최흡수"와 정합).
- ON 1s↔2s 차이 작음(짧은 펄스라 둘 다 적분기 미완).

## Ⅻ-3. 물리 확정
- 지속 토크: track·호버 둘 다 PX4 적분기가 상쇄 → bounded, hijack 약함.
- **burst: 적분기가 못 잡는 짧은 펄스 → 한방향 반복 시 누적 = hijack 성립.**
- 호버 = 임무 정지 + burst 사이 회복 → 순드리프트 봉쇄. track = 임무 날며 킥 누적 → 흐름.
- reward 와 무관(reward=탐지). 이는 **결과성 실증(①조건)** = 프레임워크 well-posed 증명.
- 그림: burst_hijack_matrix.png (막대 + 대표궤적 wp/aggr δ0.7 ON2s).

## Ⅻ-4. ★ 호버 강화 불가 — 제어-탐지 결합 (2026-08-28)
"호버를 더 강한 자세 대응으로 거의 안 움직이게" 시도 → **근본적으로 불가**. 실측(waypoint δ0.7 ON2s):
```
             봉쇄     평시 gyroNIS   공격중   분리도    임무RMSE
 기본게인      0.7m      0.36        2.52     2.16     0.34
 rate K1.8    0.5m      2.31        2.47     0.16     0.35   ← 탐지 붕괴
```
- rate 게인↑ → 봉쇄 찔끔(0.7→0.5) but **평시 NIS 0.36→2.31 폭등** → 분리도 2.16→0.16 = 탐지 사망.
- 메커니즘: 게인↑ → 모터 반응 공격적 → 각가속도 노이지 → **shadow UKF 잔차 상승** → NIS 바닥↑.
  **제어 공격성 ↔ 탐지 민감도가 잔차를 통해 결합.**
- ∴ 표준 컨트롤러 봉쇄(burst 0.4~1.2m)가 **탐지 제약 하 sweet spot**. 강한 recovery 불가.
- **설계 원칙 정당화**: "호버=fallback+검증기동, recovery 아님" — 강한 recovery 는 검증기동(센싱)을
  죽인다. 원칙이 이 트레이드오프를 이미 반영. (rate 게인 실험 코드는 폐기, 기본 게인 유지.)

## Ⅻ-5. ★ 재접근 게이트 수정 — track 무대응이 hijack 노출 (2026-08-28)
버그: 재접근(최근접 복귀)이 track 에 **항상** 걸려 무대응조차 hijack 저항 → 대비 소멸(track net 0.3m).
수정: 재접근을 **`_did_hover` 게이트**로 — 호버 후 복귀에서만 작동. 무대응 track 은 재접근 없이
임무 시간표만 따라가 hijack 노출. (online_rl_main: 호버 진입 시 _did_hover=True, 복귀 도달 시 False)
```
수정 후 (GT, waypoint δ0.7 ON2s):
  무대응 track : 순드리프트 4.5m / 최대 5.8m  ← hijack (박스 전역 흐름)
  호버        : 순드리프트 0.8m / 최대 3.9m  ← 앵커 근방 붙잡음 + 복귀
```
- track = 임무 기동(공격받으면 흐름) / hover = 정지·자세안정 / 복귀 = 호버 후 최근접점(이때만 재접근).
- 정직한 잔여: 호버도 공격축(E)으로 burst마다 ~4m 스윙(온셋 킥, 물리). N축 붙잡아 좁은 기둥 = track 과 대비.
- 그림: hijack_vs_hover_fixed.png (GT). "뭉개짐"은 GT=GPS 확인 → 코너 라운딩(물리)+공격(hijack), 버그 아님.

## Ⅻ-6. ★★ 공격 지속시간 확정 = 지속 hijacking U(40,80) (2026-08-28)
결정: burst ON U(5,20)→**U(40,80)**(4~8s). 근거 = **위협 모델**(호버 아님):
- hijacking(드론을 특정위치로 몰기)은 **본질적으로 지속적** — 짧은 펄스는 온셋킥 후 복귀라 못 몲.
- 부산물: 공격이 적분기 정착시간(~6s)보다 길어 **호버가 유의미**(정착 vs hijack). 결과성 자연 성립.
- 실측(긴 ON 6s): 버스트 내 track 이탈 7m(hijack) vs 호버 <1m 정착. (results_longon)
```
결과성 정본 (consequentiality_final.png, GT, δ0.7):
  무대응 track : 최대이탈 7.2m (박스 전역 hijack)
  호버        : 최대이탈 2.2m (앵커 1m 근방 붙잡음)
```
- **CUSUM 근거 축 이동**: "burst 온셋 붕괴"(짧은 버스트)→"오프셋(복귀)+vel채널+aliasing 강건성"(양방향
  stopping, CUSUM 단방향·vel느림). **재측정 필요.** RHUKF vs Adam(주 기여)은 공격길이 무관.
- swrl_config attack_burst_on_range=(40,80) 반영. 공격방향 WORLD_ATK_DIR(월드고정) 구현(hijack 방향성).
- 호버는 여전히 온셋킥(~2m 루프) 있음 = 물리적 하한(제어-탐지 결합). 가치=정착·누적방지·검증기동.

---


# ⅩⅢ. ★★ 본실험 로드맵 (2026-08-28 확정) — 옵티마이저 → 탐지기법 → sim2real

> 현재 진행: 옵티마이저 하이퍼파라미터 격자(batch3b, RHUKF 8 + Adam 1, [16,16]·N5·Q1e-3).
> 이 격자는 **RHUKF 최적 config 선택용** — 아래 [1]의 전처리 단계.

## [1] 옵티마이저 비교 (★ 주 기여) — 동일 구조, 옵티마이저만 교체
격자에서 **가장 성능 좋은 RHUKF 하이퍼파라미터 확정** → 그 config를 SWRL 대표로.
**5개 옵티마이저를 동일 DDQN 구조([16,16]·12D·window4)에서 옵티마이저만 다르게:**
```
① SWRL (RHUKF-FV)  — 우리 2차 최적화기 (격자 최적 config)
② Adam             — 1차 적응 (baseline)
③ BP/SGD           — 순수 역전파 (1차 기본)
④ EKF              — 확장칼만 (2차, 야코비안 선형화)
⑤ UKF              — 무향칼만 (2차, 시그마포인트)
```
- **비교 지표**: 샘플효율(F1 임계 도달 ep) + reward 수렴 + P/R/F1 + 학습곡선 분산(강건성).
- **공정성**: 관측/보상/네트워크/공격분포 동일, seed≥3. 옵티마이저만 독립변수.
- **주장**: 자연 노이즈 POMDP에서 RHUKF-FV가 Adam·SGD보다 샘플효율, EKF·UKF보다 강건/안정.

## [2] (조건부·축소 가능) 탐지 기법 비교 — 고전 통계 기법 한정
⚠ **판단(2026-08-28): [2]는 하지 않거나 최소화할 수 있다.** 기여를 **옵티마이저([1])에 집중**한다.
- 이유: 탐지기 자체를 비교하기 시작하면 "그럼 QUADFormer·transformer 등 다른 탐지 **모델**과도
  다 비교해야 하지 않나?"라는 **스코프 확장 요구**를 부른다. 우리 기여는 탐지 SOTA 경쟁이 아니라
  **동일 탐지 문제에서 옵티마이저(2차 RHUKF-FV)의 샘플효율·강건성**이다. 그 초점을 흐리지 않는다.
- 만약 한다면 **고전 통계 기법 한정**(학습 모델 비교 금지)으로만:
  `CUSUM(QCD) · Euclidean(잔차노름) · Chi-square(NIS χ²) · 고정임계`.
  이들은 "학습 없이 못 푸는 문제"임을 보이는 **하한 baseline** 역할(모델 경쟁 아님).
- [1]과 **병행 가능**(같은 학습 산출물 재사용). 단 지도교수 방향이 "옵티마이저만"이면 **생략**.
- 지표(할 경우): P/R/F1 + 양방향 지연 + FPR 캘리브(1%).

## [3] sim-to-real 이관 — online play 실기 검증
[1]·[2] 확정 후 **학습된 에이전트를 실기체에 이관, 실제 online 탐지 성능 검증:**
```
· 플랜트 정합(이미 대부분 완료: 질량·C_torque·모터지연·gyroσ·MPC제한)
· 실기 f5_pattern.py 에 line/코너감속/scurve 궤적 이식
· 실기 FDI 공격 주입(ControlAllocator c[0], 이미 SITL 검증) → 실비행 online play
· sim vs real 탐지 성능 대조 (P/R/F1, NIS 기준선, 펄스 시그니처)
```
- **목표**: sim에서 학습한 탐지기가 실기 실제 공격을 online으로 탐지 = sim2real 전이 입증.

## 파이프라인 요약
```
격자(RHUKF config 선택) → [1]옵티마이저5종 비교 → ([2]고전 baseline·조건부) → [3]실기 online play
        (진행 중)              (★주 기여·집중)        (생략 가능·스코프 방어)      (sim2real 검증)
```

---


# ⅩⅣ. NIS 거동 총분석 + 정규화 u 검증 (2026-08-28, config E, 오프라인)

## ⅩⅣ-1. NIS 조건별 (results_final2/flip, 현재 config)
```
조건                        gyroNIS 평균  p90   p99   max  >1.5%  velNIS
① 평시 기동(무공격·무풍)        0.64      1.46  -     2.62   -     0.53
② 기동+공격 track(PX4보상)     2.14      2.52  -     3.00  99%    0.68
③ 호버+공격(대응중)           2.15      2.49  -     2.82  99%    0.69
④ scurve 기동(무공격)         0.68      1.69  2.27  2.62  15%    0.53
⑤ waypoint 기동(무공격)       0.60      1.25  1.69  1.98   3%    -
⑥ 바람 ws8(무공격)            0.46      0.70  1.47  1.67   1%    0.51
⑦ 호버 전환 순간(0→1, 공격중)  1.92      2.53  -     2.82   -     0.65
```
- **Q1 답(★): PX4가 공격 흡수해 궤적 유지해도 gyro NIS 상승**(0.64→2.14). shadow UKF는 명령 토크로
  예측하나 실제엔 δ 가산 → 잔차 유지. **kinematic 흡수 ≠ residual 은폐.** (nis_analysis.png)
- **Q2 답: 공격 중 호버해도 NIS 유지**(2.15). 호버가 공격 토크를 못 없애서.
- **Q4 답: 바람·기동은 gyro NIS 를 평균적으론 안 올림**(0.46~0.68).

## ⅩⅣ-2. ★ aliasing 정정 — 평균 아니라 스파이크로 봐야 (원웅 지적)
평균만 보면 기동/바람이 trivial(0.5~0.7)해 보이나 **aliasing 은 "가끔 튀는 스파이크"다:**
```
scurve 기동  : p99 2.27·max 2.62·15%가 >1.5  ← 순간 공격수준(공격평균 2.32)까지 튐
바람         : p99 1.47 (가끔)
공격         : 99% >1.5·지속        ← 항상 높음
```
- **핵심 구분 = 지속(공격) vs 순간(기동 aliasing).** 분포 겹침(기동 꼬리 ↔ 공격 봉우리) = aliasing.
- 단일프레임 임계론 못 가름(순간엔 동일) → **윈도우 시간패턴(RL)이 지속/순간 구분 = RL 정당화.**
- 공격 종료 후 gyro NIS 빠른 급락(τoff~7) 관측 = sweet spot Q/R 유지됨. (gyro_aliasing.png)
- ∴ 프레임워크(gyro aliasing·즉시가시·빠른 오프셋)는 **반영돼 있음**. 평균 제시가 오해를 부른 것.

## ⅩⅣ-3. 선배 검증 — 정규화 PX4 제어입력(C 없이) UKF
zu_log (z,u) 오프라인 재생, u_phys vs u_norm(=u_phys/C):
```
무공격:   gyroNIS  vel NIS  gyro추종  vel추종
 물리 u    0.81     0.41    0.268    0.070
 정규화 u  0.48     2.19    0.116    0.993m/s   ← vel 붕괴
gyro 공격탐지: 물리 0.84→2.20(분리+1.37) / 정규화 0.48→1.27(분리+0.78)
```
- **✅ gyro/자세 채널: 정규화 u OK** — 추종 더 좋고 공격 탐지도 됨(분리 +0.78). 평시 토크 작아
  스케일 영향 미미. **틸트공격 주채널이 gyro 라 선배 직관 유효.**
- **❌ vel/추력: C_thrust 필수** — 추력이 중력(mg=13.1N)을 물리단위로 상쇄해야. 정규화(0.32) → 자유낙하.
- **⚠ gyro 탐지도 ~40% 약화**(분리 +0.78 vs +1.37). C_torque 정밀도가 탐지 감도.
- 정리: **C_torque 생략가능(gyro 40%약화)·C_thrust 필수(vel).** 우리는 둘다 쓰니 C_thrust 유지. (normalized_u_test.png)

## ⅩⅣ-4. ⬜ TODO (학습 후 캡처) — 무공격 exploration 호버 전환 NIS
현재 whover2 는 공격 중에만 호버 → ⑦(1.92)은 공격과 섞임. **무공격 중 급기동→갑자기 호버(exploration
랜덤행동) 전환 시 NIS 스파이크 여부**는 깨끗한 답을 위해 별도 캡처 필요(격자 학습 후).
가설: 급정지 감속 과도로 vel NIS 순간 bump 가능, gyro 는 미미. FP 원천 점검용.
